### ISSUE TITLE
up to jump & endless

### ISSUE THREAD

**Issue by Romanista345** [markus-zzz/myc64-pocket#4]
hi great work there,

two requests:

colt you map 'up' on the controller also to a button, so you don't have up to jump anymore in games like great Giana sisters.

and I think you mentions it yourself sprite v background collections don't work... game in point 'Endless' where I can just chopper everywhere (as can the opponents)..

and you might add that in the unload collection the org's are a bit hiding (Ince it presents you with .crt first, and prg 's are an 'alternative format'. 

have a lovely weekend

**Comment by markus-zzz** [comment]
Thanks 

Yes, stick for jumping an button for throwing rubber ball is not up to date with what one expect nowadays. You may be able to fix that with the APF json files

https://www.analogue.co/developer/docs/core-definition-files/input-json

If you come up with anything good then setup a pull request and we'll integrate it.

Background is known but didn't have a good testcase so that is good that you reported.

Will fix the other stuff later today when back at my workstation.

**Comment by lunchpacked130** [comment]
I think the best solution would be to have a duplicate up/down command permanently mapped to face buttons.

Seeing as the c64 only uses a single joystick button anyway (except a small handful of games that supports up to 2 buttons) there are atleast 2 unused face buttons that could be bound as up/down, and hopefully by then, the configure controls settings for the core will work so you can map it how you want it.

Another alternative would be to have a toggle switch in core settings to switch [Up] and [Down] from dpad to face buttons, in case having the same action mapped to two different buttons causes issues.

**Comment by markus-zzz** [comment]
The lack of collision detection with background in game `Endless` has been addressed in https://github.com/markus-zzz/myc64-pocket/releases/tag/v0.1.1
