### ISSUE TITLE
Rolling Thunder - Graphical glitches

### ISSUE THREAD

**Issue by harlock74** [markus-zzz/myc64-pocket#9]
Hi,
When I load Rolling Thunder the screen looks like squashed vertically, sort of 16:9 aspect ratio with a black area at the bottom of the screen itself. Also the player and the enemy appear sort of offset from the platform level.
Please refer to the attached screenshot.
Thanks!

![Image](https://github.com/markus-zzz/myc64-pocket/assets/4136670/2ec54d51-a76f-45f8-9a58-1b0a7353e9fc)

**Comment by markus-zzz** [comment]
Characters being offset is due to 'Height doubling' register `$d017` not being implemented yet (verified with VICE).

For the other part it should look like this
![vice-screen-20240416212118](https://github.com/markus-zzz/myc64-pocket/assets/8939552/9c61602a-9570-4099-895d-e0e7aa065e11)
There is a raster interrupt at the position (I think) where the 'Rolling Thunder' footer is to be displayed and it does change the vic-ii memory bank. Also at this point, for one raster line, the graphics mode is changed into an invalid one 1/1/1.
![invalid-mode](https://github.com/markus-zzz/myc64-pocket/assets/8939552/89caa548-738e-4abe-928e-2df66fcfabb6)

Weird.. The sprite double should be an easy fix though.

**Comment by harlock74** [comment]
Awesome! Thanks a lot for looking at it!

**Comment by markus-zzz** [comment]
Slow progress here..

When looking at #18 it was discovered that the 'display enable' bit in register `$d011` may be implemented incorrectly. Ignoring the bit, and always being in a display enabled mode gives the following result

![vicii-0625](https://github.com/markus-zzz/myc64-pocket/assets/8939552/39f57307-6d74-44eb-a91c-3fc913d03289)

so fixing that and the sprite doubling should resolve this ticket.

**Comment by harlock74** [comment]
Great news,
Thank you so much. I can't wait to give it a go!

**Comment by markus-zzz** [comment]
Finally resolved as of `v0.2.2`

**Comment by harlock74** [comment]
Awesome news! Many thanks for that. Much appreciated.
